const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp();

// Database reference
const db = admin.firestore();

// WhatsApp Notification Function
exports.sendWhatsAppNotification = functions.firestore
  .document('marks/{marksId}')
  .onCreate(async (snap, context) => {
    try {
      const marksData = snap.data();
      
      // Get student details
      const studentDoc = await db.collection('students').doc(marksData.studentId).get();
      if (!studentDoc.exists) {
        console.log('Student not found');
        return null;
      }
      
      const student = studentDoc.data();
      
      // Get exam details
      const examDoc = await db.collection('exams').doc(marksData.examId).get();
      if (!examDoc.exists) {
        console.log('Exam not found');
        return null;
      }
      
      const exam = examDoc.data();
      
      // Build WhatsApp message
      let message = `📚 *${process.env.SCHOOL_NAME || 'School Name'}*\n\n`;
      message += `*Student Report Card*\n\n`;
      message += `👤 *Student Name:* ${student.name}\n`;
      message += `🎓 *Class:* ${student.class} - ${student.section}\n`;
      message += `📋 *Exam:* ${exam.name}\n\n`;
      message += `*Subject-wise Marks:*\n`;
      message += `─────────────────\n`;
      
      marksData.subjects.forEach(subject => {
        const status = subject.isPassed ? '✅' : '❌';
        message += `📖 ${subject.subjectName}: ${subject.obtainedMarks}/${subject.maxMarks} (${subject.percentage}%) ${status}\n`;
      });
      
      message += `─────────────────\n\n`;
      message += `📊 *Total:* ${marksData.totalObtained}/${marksData.totalMaximum}\n`;
      message += `📈 *Percentage:* ${marksData.overallPercentage}%\n`;
      message += `🏆 *Grade:* ${marksData.overallGrade}\n`;
      message += `❌ *Failed Subjects:* ${marksData.failedSubjects}\n\n`;
      
      const promotionStatus = marksData.isPromoted ? '✅ PROMOTED' : '❌ NOT PROMOTED';
      message += `🎯 *Status:* ${promotionStatus}\n\n`;
      
      if (marksData.remark) {
        message += `📝 *Teacher's Remark:* ${marksData.remark}\n\n`;
      }
      
      message += `─────────────────\n`;
      message += `*Generated by School Mark System*`;
      
      // Send WhatsApp message
      // Note: Replace with your actual WhatsApp API
      // Options: Twilio, Gupshup, or other WhatsApp Business API providers
      
      // For free mode, we'll log the message and create a notification record
      console.log('WhatsApp Message to send:', message);
      console.log('Phone number:', student.parentPhone);
      
      // Create notification log
      await db.collection('notifications').add({
        type: 'whatsapp',
        studentId: marksData.studentId,
        examId: marksData.examId,
        marksId: context.params.marksId,
        phone: student.parentPhone,
        message: message,
        status: 'logged', // Change to 'sent' when using actual API
        sentAt: admin.firestore.FieldValue.serverTimestamp()
      });
      
      // Uncomment below to use actual WhatsApp API
      /*
      // Example using Twilio (requires Twilio account)
      const twilio = require('twilio');
      const client = twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN);
      
      await client.messages.create({
        from: 'whatsapp:' + process.env.TWILIO_WHATSAPP_NUMBER,
        to: 'whatsapp:' + student.parentPhone,
        body: message
      });
      */
      
      return null;
    } catch (error) {
      console.error('Error sending WhatsApp notification:', error);
      return null;
    }
  });

// Send WhatsApp notification when marks are updated
exports.sendWhatsAppOnUpdate = functions.firestore
  .document('marks/{marksId}')
  .onUpdate(async (change, context) => {
    try {
      const marksData = change.after.data();
      
      // Get student details
      const studentDoc = await db.collection('students').doc(marksData.studentId).get();
      if (!studentDoc.exists) {
        console.log('Student not found');
        return null;
      }
      
      const student = studentDoc.data();
      
      // Get exam details
      const examDoc = await db.collection('exams').doc(marksData.examId).get();
      if (!examDoc.exists) {
        console.log('Exam not found');
        return null;
      }
      
      const exam = examDoc.data();
      
      // Build WhatsApp message for update
      let message = `📚 *${process.env.SCHOOL_NAME || 'School Name'}*\n\n`;
      message += `🔄 *Marks Updated*\n\n`;
      message += `👤 *Student Name:* ${student.name}\n`;
      message += `🎓 *Class:* ${student.class} - ${student.section}\n`;
      message += `📋 *Exam:* ${exam.name}\n\n`;
      message += `*Updated Marks:*\n`;
      message += `─────────────────\n`;
      
      marksData.subjects.forEach(subject => {
        const status = subject.isPassed ? '✅' : '❌';
        message += `📖 ${subject.subjectName}: ${subject.obtainedMarks}/${subject.maxMarks} (${subject.percentage}%) ${status}\n`;
      });
      
      message += `─────────────────\n\n`;
      message += `📊 *Total:* ${marksData.totalObtained}/${marksData.totalMaximum}\n`;
      message += `📈 *Percentage:* ${marksData.overallPercentage}%\n`;
      message += `🏆 *Grade:* ${marksData.overallGrade}\n\n`;
      
      const promotionStatus = marksData.isPromoted ? '✅ PROMOTED' : '❌ NOT PROMOTED';
      message += `🎯 *Status:* ${promotionStatus}\n\n`;
      message += `─────────────────\n`;
      message += `*Generated by School Mark System*`;
      
      // Log the update notification
      console.log('WhatsApp Update Message:', message);
      
      await db.collection('notifications').add({
        type: 'whatsapp_update',
        studentId: marksData.studentId,
        examId: marksData.examId,
        marksId: context.params.marksId,
        phone: student.parentPhone,
        message: message,
        status: 'logged',
        sentAt: admin.firestore.FieldValue.serverTimestamp()
      });
      
      return null;
    } catch (error) {
      console.error('Error sending WhatsApp update notification:', error);
      return null;
    }
  });

// Calculate class ranks after marks are submitted
exports.calculateClassRank = functions.firestore
  .document('marks/{marksId}')
  .onCreate(async (snap, context) => {
    try {
      const marksData = snap.data();
      
      // Get exam details to find the class
      const examDoc = await db.collection('exams').doc(marksData.examId).get();
      if (!examDoc.exists) {
        return null;
      }
      
      const exam = examDoc.data();
      
      // Get all marks for this exam
      const marksSnapshot = await db.collection('marks')
        .where('examId', '==', marksData.examId)
        .get();
      
      if (marksSnapshot.empty) {
        return null;
      }
      
      // Sort students by percentage (descending)
      const studentsMarks = [];
      marksSnapshot.forEach(doc => {
        studentsMarks.push({
          id: doc.id,
          studentId: doc.data().studentId,
          percentage: doc.data().overallPercentage,
          totalObtained: doc.data().totalObtained
        });
      });
      
      studentsMarks.sort((a, b) => b.percentage - a.percentage);
      
      // Update ranks
      const batch = db.batch();
      studentsMarks.forEach((studentMark, index) => {
        const marksRef = db.collection('marks').doc(studentMark.id);
        batch.update(marksRef, { rank: index + 1 });
      });
      
      await batch.commit();
      
      console.log(`Ranks calculated for exam ${exam.name}, Class ${exam.class}`);
      return null;
    } catch (error) {
      console.error('Error calculating class ranks:', error);
      return null;
    }
  });

// Scheduled function to backup data daily (optional)
exports.scheduledBackup = functions.pubsub
  .schedule('0 2 * * *')
  .timeZone('Asia/Kolkata')
  .onRun(async (context) => {
    try {
      console.log('Starting scheduled backup...');
      
      // Backup students
      const studentsSnapshot = await db.collection('students').get();
      const studentsBackup = [];
      studentsSnapshot.forEach(doc => {
        studentsBackup.push({ id: doc.id, ...doc.data() });
      });
      
      // Backup marks
      const marksSnapshot = await db.collection('marks').get();
      const marksBackup = [];
      marksSnapshot.forEach(doc => {
        marksBackup.push({ id: doc.id, ...doc.data() });
      });
      
      // Save backup (you can save to Cloud Storage or another collection)
      await db.collection('backups').add({
        type: 'daily',
        students: studentsBackup,
        marks: marksBackup,
        timestamp: admin.firestore.FieldValue.serverTimestamp()
      });
      
      console.log('Backup completed successfully');
      return null;
    } catch (error) {
      console.error('Error during backup:', error);
      return null;
    }
  });